# Generated by Django 4.0.2 on 2022-02-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='instagram',
            field=models.CharField(default='#', max_length=100, verbose_name='Instagram'),
        ),
    ]
