# Generated by Django 4.0.2 on 2022-03-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_precos'),
    ]

    operations = [
        migrations.AddField(
            model_name='precos',
            name='icones',
            field=models.CharField(choices=[('lni-package', 'Pacote'), ('lni-drop', 'Gota'), ('lni-star', 'Estrela')], default='lni-drop', max_length=11, verbose_name='Ícone'),
        ),
    ]
