# Generated by Django 4.0.2 on 2022-03-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_precos_icones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precos',
            old_name='icones',
            new_name='icone',
        ),
    ]
