# Generated by Django 4.0.2 on 2022-03-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_icones_precos_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('titulo', models.CharField(max_length=15, verbose_name='Título')),
                ('qtd_usuario', models.CharField(max_length=20, verbose_name='Quantidade de Usuário')),
                ('armazenamento', models.IntegerField(verbose_name='Armazenamento')),
                ('icone', models.CharField(choices=[('lni-package', 'Pacote'), ('lni-drop', 'Gota'), ('lni-star', 'Estrela')], default='lni-drop', max_length=11, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Preço',
                'verbose_name_plural': 'Preços',
            },
        ),
        migrations.DeleteModel(
            name='Precos',
        ),
    ]
