# Generated by Django 4.0.2 on 2022-03-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_preco_delete_precos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preco',
            name='preco',
        ),
        migrations.AddField(
            model_name='preco',
            name='precos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Preço'),
        ),
    ]
