# Generated by Django 4.0.2 on 2022-03-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_preco_preco_preco_precos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preco',
            name='icone',
            field=models.CharField(choices=[('lni-package', 'Pacote'), ('lni-drop', 'Gota'), ('lni-star', 'Estrela')], max_length=11, verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='preco',
            name='precos',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço'),
        ),
    ]
