# Generated by Django 4.0.2 on 2022-03-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_preco_icone_alter_preco_precos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preco',
            name='armazenamento',
            field=models.CharField(max_length=4, verbose_name='Armazenamento'),
        ),
        migrations.AlterField(
            model_name='preco',
            name='precos',
            field=models.CharField(max_length=5, verbose_name='Preço'),
        ),
    ]
